title: Robbie's awesome title
author: robbiegay
email: robbiecgay@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is where I write an awesome description of my site.

# social links
twitter_username: @notontwitter
github_username:  @robbiegay

show_excerpts: true # set to false to remove excerpts on the homepage
